[2022-11-29 14:17:37,503] {processor.py:153} INFO - Started process (PID=520) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:37,504] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:17:37,504] {logging_mixin.py:115} INFO - [2022-11-29 14:17:37,504] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:37,521] {logging_mixin.py:115} INFO - [2022-11-29 14:17:37,520] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 32, in <module>
    start_datetime=datetime.datetime.now() - datetime.timedelta(days=2),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-11-29 14:17:37,521] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:37,541] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.040 seconds
[2022-11-29 14:17:38,516] {processor.py:153} INFO - Started process (PID=531) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:38,516] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:17:38,517] {logging_mixin.py:115} INFO - [2022-11-29 14:17:38,517] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:38,521] {logging_mixin.py:115} INFO - [2022-11-29 14:17:38,520] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 31, in <module>
    start_datetime=datetime.datetime.now() - datetime.timedelta(days=2),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-11-29 14:17:38,521] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:38,533] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.019 seconds
[2022-11-29 14:17:42,542] {processor.py:153} INFO - Started process (PID=532) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:42,548] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:17:42,550] {logging_mixin.py:115} INFO - [2022-11-29 14:17:42,550] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:42,566] {logging_mixin.py:115} INFO - [2022-11-29 14:17:42,565] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 31, in <module>
    start_datetime=datetime.datetime.now() - datetime.timedelta(days=2),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-11-29 14:17:42,567] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:42,592] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.058 seconds
[2022-11-29 14:17:44,561] {processor.py:153} INFO - Started process (PID=533) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:44,561] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:17:44,562] {logging_mixin.py:115} INFO - [2022-11-29 14:17:44,561] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:44,566] {logging_mixin.py:115} INFO - [2022-11-29 14:17:44,565] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 31, in <module>
    start_datetime=datetime.datetime.now() - datetime.timedelta(days=2),
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2022-11-29 14:17:44,566] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:44,579] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.020 seconds
[2022-11-29 14:17:50,604] {processor.py:153} INFO - Started process (PID=543) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:50,605] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:17:50,606] {logging_mixin.py:115} INFO - [2022-11-29 14:17:50,606] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:50,612] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:50,624] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.023 seconds
[2022-11-29 14:17:51,607] {processor.py:153} INFO - Started process (PID=544) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:51,607] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:17:51,607] {logging_mixin.py:115} INFO - [2022-11-29 14:17:51,607] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:51,610] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:17:51,618] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.013 seconds
[2022-11-29 14:18:21,687] {processor.py:153} INFO - Started process (PID=563) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:18:21,689] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:18:21,689] {logging_mixin.py:115} INFO - [2022-11-29 14:18:21,689] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:18:21,692] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:18:21,699] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 14:18:33,719] {processor.py:153} INFO - Started process (PID=574) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:18:33,720] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:18:33,720] {logging_mixin.py:115} INFO - [2022-11-29 14:18:33,720] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:18:33,721] {logging_mixin.py:115} INFO - [2022-11-29 14:18:33,721] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 57
    t1 = PythonOperator(
     ^
IndentationError: expected an indented block
[2022-11-29 14:18:33,721] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:18:33,734] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.017 seconds
[2022-11-29 14:18:37,754] {processor.py:153} INFO - Started process (PID=584) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:18:37,760] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:18:37,761] {logging_mixin.py:115} INFO - [2022-11-29 14:18:37,761] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:18:37,767] {logging_mixin.py:115} INFO - [2022-11-29 14:18:37,765] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:18:37,768] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:18:37,814] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.067 seconds
[2022-11-29 14:19:07,889] {processor.py:153} INFO - Started process (PID=604) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:19:07,890] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:19:07,892] {logging_mixin.py:115} INFO - [2022-11-29 14:19:07,891] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:19:07,898] {logging_mixin.py:115} INFO - [2022-11-29 14:19:07,896] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:19:07,899] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:19:07,932] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.050 seconds
[2022-11-29 14:19:37,976] {processor.py:153} INFO - Started process (PID=631) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:19:37,978] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:19:37,979] {logging_mixin.py:115} INFO - [2022-11-29 14:19:37,979] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:19:37,984] {logging_mixin.py:115} INFO - [2022-11-29 14:19:37,982] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:19:37,984] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:19:38,039] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.071 seconds
[2022-11-29 14:20:08,107] {processor.py:153} INFO - Started process (PID=659) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:20:08,107] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:20:08,107] {logging_mixin.py:115} INFO - [2022-11-29 14:20:08,107] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:20:08,109] {logging_mixin.py:115} INFO - [2022-11-29 14:20:08,108] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:20:08,109] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:20:08,120] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 14:50:26,033] {processor.py:153} INFO - Started process (PID=678) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:50:26,035] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:50:26,036] {logging_mixin.py:115} INFO - [2022-11-29 14:50:26,036] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:50:26,043] {logging_mixin.py:115} INFO - [2022-11-29 14:50:26,041] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:50:26,044] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:50:26,209] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.187 seconds
[2022-11-29 14:50:56,278] {processor.py:153} INFO - Started process (PID=706) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:50:56,279] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:50:56,280] {logging_mixin.py:115} INFO - [2022-11-29 14:50:56,280] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:50:56,283] {logging_mixin.py:115} INFO - [2022-11-29 14:50:56,282] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:50:56,283] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:50:56,308] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.034 seconds
[2022-11-29 14:51:26,361] {processor.py:153} INFO - Started process (PID=726) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:51:26,366] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:51:26,367] {logging_mixin.py:115} INFO - [2022-11-29 14:51:26,367] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:51:26,368] {logging_mixin.py:115} INFO - [2022-11-29 14:51:26,368] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:51:26,368] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:51:26,381] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 14:51:56,428] {processor.py:153} INFO - Started process (PID=755) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:51:56,433] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:51:56,433] {logging_mixin.py:115} INFO - [2022-11-29 14:51:56,433] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:51:56,435] {logging_mixin.py:115} INFO - [2022-11-29 14:51:56,434] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:51:56,435] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:51:56,447] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 14:52:26,499] {processor.py:153} INFO - Started process (PID=784) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:52:26,504] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:52:26,505] {logging_mixin.py:115} INFO - [2022-11-29 14:52:26,505] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:52:26,506] {logging_mixin.py:115} INFO - [2022-11-29 14:52:26,506] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:52:26,506] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:52:26,519] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 14:52:56,563] {processor.py:153} INFO - Started process (PID=803) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:52:56,568] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:52:56,568] {logging_mixin.py:115} INFO - [2022-11-29 14:52:56,568] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:52:56,569] {logging_mixin.py:115} INFO - [2022-11-29 14:52:56,569] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:52:56,569] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:52:56,581] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.020 seconds
[2022-11-29 14:53:26,629] {processor.py:153} INFO - Started process (PID=832) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:53:26,634] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:53:26,635] {logging_mixin.py:115} INFO - [2022-11-29 14:53:26,635] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:53:26,636] {logging_mixin.py:115} INFO - [2022-11-29 14:53:26,635] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:53:26,636] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:53:26,648] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 14:53:56,698] {processor.py:153} INFO - Started process (PID=860) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:53:56,704] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:53:56,704] {logging_mixin.py:115} INFO - [2022-11-29 14:53:56,704] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:53:56,705] {logging_mixin.py:115} INFO - [2022-11-29 14:53:56,705] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:53:56,706] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:53:56,718] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 14:54:26,765] {processor.py:153} INFO - Started process (PID=886) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:54:26,771] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:54:26,773] {logging_mixin.py:115} INFO - [2022-11-29 14:54:26,773] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:54:26,783] {logging_mixin.py:115} INFO - [2022-11-29 14:54:26,781] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:54:26,784] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:54:26,807] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.045 seconds
[2022-11-29 14:54:56,828] {processor.py:153} INFO - Started process (PID=908) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:54:56,828] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:54:56,828] {logging_mixin.py:115} INFO - [2022-11-29 14:54:56,828] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:54:56,829] {logging_mixin.py:115} INFO - [2022-11-29 14:54:56,829] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:54:56,830] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:54:56,841] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 14:55:26,910] {processor.py:153} INFO - Started process (PID=937) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:55:26,911] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:55:26,912] {logging_mixin.py:115} INFO - [2022-11-29 14:55:26,912] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:55:26,917] {logging_mixin.py:115} INFO - [2022-11-29 14:55:26,915] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:55:26,918] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:55:26,933] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.031 seconds
[2022-11-29 14:55:56,980] {processor.py:153} INFO - Started process (PID=956) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:55:56,985] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:55:56,986] {logging_mixin.py:115} INFO - [2022-11-29 14:55:56,986] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:55:56,993] {logging_mixin.py:115} INFO - [2022-11-29 14:55:56,990] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:55:56,993] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:55:57,035] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.057 seconds
[2022-11-29 14:56:27,074] {processor.py:153} INFO - Started process (PID=985) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:56:27,075] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 14:56:27,075] {logging_mixin.py:115} INFO - [2022-11-29 14:56:27,075] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:56:27,080] {logging_mixin.py:115} INFO - [2022-11-29 14:56:27,078] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 14:56:27,080] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 14:56:27,099] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.031 seconds
[2022-11-29 16:18:01,018] {processor.py:153} INFO - Started process (PID=1013) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:18:01,019] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:18:01,021] {logging_mixin.py:115} INFO - [2022-11-29 16:18:01,021] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:18:01,029] {logging_mixin.py:115} INFO - [2022-11-29 16:18:01,027] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:18:01,030] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:18:01,077] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.071 seconds
[2022-11-29 16:18:31,136] {processor.py:153} INFO - Started process (PID=1041) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:18:31,136] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:18:31,137] {logging_mixin.py:115} INFO - [2022-11-29 16:18:31,137] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:18:31,139] {logging_mixin.py:115} INFO - [2022-11-29 16:18:31,138] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:18:31,139] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:18:31,159] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.026 seconds
[2022-11-29 16:19:01,206] {processor.py:153} INFO - Started process (PID=1060) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:19:01,206] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:19:01,207] {logging_mixin.py:115} INFO - [2022-11-29 16:19:01,207] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:19:01,208] {logging_mixin.py:115} INFO - [2022-11-29 16:19:01,208] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:19:01,208] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:19:01,221] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.017 seconds
[2022-11-29 16:19:31,292] {processor.py:153} INFO - Started process (PID=1088) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:19:31,293] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:19:31,295] {logging_mixin.py:115} INFO - [2022-11-29 16:19:31,294] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:19:31,301] {logging_mixin.py:115} INFO - [2022-11-29 16:19:31,299] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:19:31,301] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:19:31,352] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.067 seconds
[2022-11-29 16:20:01,403] {processor.py:153} INFO - Started process (PID=1107) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:20:01,404] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:20:01,404] {logging_mixin.py:115} INFO - [2022-11-29 16:20:01,404] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:20:01,406] {logging_mixin.py:115} INFO - [2022-11-29 16:20:01,406] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:20:01,407] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:20:01,427] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.027 seconds
[2022-11-29 16:20:31,470] {processor.py:153} INFO - Started process (PID=1135) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:20:31,475] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:20:31,476] {logging_mixin.py:115} INFO - [2022-11-29 16:20:31,476] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:20:31,477] {logging_mixin.py:115} INFO - [2022-11-29 16:20:31,477] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:20:31,477] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:20:31,492] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.023 seconds
[2022-11-29 16:21:01,566] {processor.py:153} INFO - Started process (PID=1163) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:21:01,567] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:21:01,568] {logging_mixin.py:115} INFO - [2022-11-29 16:21:01,568] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:21:01,574] {logging_mixin.py:115} INFO - [2022-11-29 16:21:01,572] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:21:01,574] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:21:01,606] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.047 seconds
[2022-11-29 16:21:31,633] {processor.py:153} INFO - Started process (PID=1182) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:21:31,633] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:21:31,633] {logging_mixin.py:115} INFO - [2022-11-29 16:21:31,633] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:21:31,635] {logging_mixin.py:115} INFO - [2022-11-29 16:21:31,634] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:21:31,635] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:21:31,649] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.019 seconds
[2022-11-29 16:22:01,735] {processor.py:153} INFO - Started process (PID=1210) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:22:01,736] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:22:01,736] {logging_mixin.py:115} INFO - [2022-11-29 16:22:01,736] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:22:01,740] {logging_mixin.py:115} INFO - [2022-11-29 16:22:01,739] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:22:01,740] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:22:01,760] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.028 seconds
[2022-11-29 16:22:31,802] {processor.py:153} INFO - Started process (PID=1238) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:22:31,807] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:22:31,807] {logging_mixin.py:115} INFO - [2022-11-29 16:22:31,807] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:22:31,809] {logging_mixin.py:115} INFO - [2022-11-29 16:22:31,808] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:22:31,809] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:22:31,821] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 16:23:01,911] {processor.py:153} INFO - Started process (PID=1257) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:23:01,912] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:23:01,912] {logging_mixin.py:115} INFO - [2022-11-29 16:23:01,912] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:23:01,917] {logging_mixin.py:115} INFO - [2022-11-29 16:23:01,915] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:23:01,917] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:23:01,951] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.046 seconds
[2022-11-29 16:23:31,983] {processor.py:153} INFO - Started process (PID=1285) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:23:31,999] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:23:32,000] {logging_mixin.py:115} INFO - [2022-11-29 16:23:32,000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:23:32,030] {logging_mixin.py:115} INFO - [2022-11-29 16:23:32,029] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:23:32,031] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:23:32,046] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.065 seconds
[2022-11-29 16:24:02,084] {processor.py:153} INFO - Started process (PID=1304) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:24:02,085] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:24:02,085] {logging_mixin.py:115} INFO - [2022-11-29 16:24:02,085] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:24:02,086] {logging_mixin.py:115} INFO - [2022-11-29 16:24:02,086] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:24:02,086] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:24:02,098] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 16:24:32,159] {processor.py:153} INFO - Started process (PID=1331) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:24:32,159] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:24:32,159] {logging_mixin.py:115} INFO - [2022-11-29 16:24:32,159] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:24:32,161] {logging_mixin.py:115} INFO - [2022-11-29 16:24:32,161] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:24:32,161] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:24:32,175] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.018 seconds
[2022-11-29 16:25:02,237] {processor.py:153} INFO - Started process (PID=1359) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:25:02,237] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:25:02,237] {logging_mixin.py:115} INFO - [2022-11-29 16:25:02,237] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:25:02,238] {logging_mixin.py:115} INFO - [2022-11-29 16:25:02,238] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:25:02,239] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:25:02,250] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 16:25:32,329] {processor.py:153} INFO - Started process (PID=1378) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:25:32,335] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:25:32,337] {logging_mixin.py:115} INFO - [2022-11-29 16:25:32,337] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:25:32,343] {logging_mixin.py:115} INFO - [2022-11-29 16:25:32,342] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:25:32,344] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:25:32,370] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.050 seconds
[2022-11-29 16:26:02,408] {processor.py:153} INFO - Started process (PID=1407) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:26:02,414] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:26:02,415] {logging_mixin.py:115} INFO - [2022-11-29 16:26:02,415] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:26:02,421] {logging_mixin.py:115} INFO - [2022-11-29 16:26:02,419] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:26:02,422] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:26:02,460] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.053 seconds
[2022-11-29 16:26:32,506] {processor.py:153} INFO - Started process (PID=1435) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:26:32,507] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:26:32,507] {logging_mixin.py:115} INFO - [2022-11-29 16:26:32,507] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:26:32,510] {logging_mixin.py:115} INFO - [2022-11-29 16:26:32,509] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:26:32,510] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:26:32,528] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.025 seconds
[2022-11-29 16:27:02,574] {processor.py:153} INFO - Started process (PID=1454) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:27:02,574] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:27:02,574] {logging_mixin.py:115} INFO - [2022-11-29 16:27:02,574] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:27:02,576] {logging_mixin.py:115} INFO - [2022-11-29 16:27:02,575] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:27:02,576] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:27:02,588] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.016 seconds
[2022-11-29 16:27:32,651] {processor.py:153} INFO - Started process (PID=1482) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:27:32,651] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:27:32,652] {logging_mixin.py:115} INFO - [2022-11-29 16:27:32,652] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:27:32,653] {logging_mixin.py:115} INFO - [2022-11-29 16:27:32,653] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:27:32,653] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:27:32,668] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.018 seconds
[2022-11-29 16:28:02,759] {processor.py:153} INFO - Started process (PID=1506) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:28:02,760] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:28:02,760] {logging_mixin.py:115} INFO - [2022-11-29 16:28:02,760] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:28:02,763] {logging_mixin.py:115} INFO - [2022-11-29 16:28:02,762] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:28:02,764] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:28:02,794] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.039 seconds
[2022-11-29 16:28:32,837] {processor.py:153} INFO - Started process (PID=1528) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:28:32,837] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:28:32,837] {logging_mixin.py:115} INFO - [2022-11-29 16:28:32,837] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:28:32,839] {logging_mixin.py:115} INFO - [2022-11-29 16:28:32,838] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:28:32,839] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:28:32,851] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.016 seconds
[2022-11-29 16:29:02,922] {processor.py:153} INFO - Started process (PID=1556) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:29:02,923] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:29:02,923] {logging_mixin.py:115} INFO - [2022-11-29 16:29:02,923] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:29:02,924] {logging_mixin.py:115} INFO - [2022-11-29 16:29:02,924] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:29:02,925] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:29:02,939] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.018 seconds
[2022-11-29 16:29:33,001] {processor.py:153} INFO - Started process (PID=1575) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:29:33,001] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:29:33,001] {logging_mixin.py:115} INFO - [2022-11-29 16:29:33,001] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:29:33,002] {logging_mixin.py:115} INFO - [2022-11-29 16:29:33,002] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:29:33,002] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:29:33,014] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 16:30:03,080] {processor.py:153} INFO - Started process (PID=1603) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:30:03,085] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:30:03,085] {logging_mixin.py:115} INFO - [2022-11-29 16:30:03,085] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:30:03,087] {logging_mixin.py:115} INFO - [2022-11-29 16:30:03,086] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:30:03,087] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:30:03,099] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 16:30:33,154] {processor.py:153} INFO - Started process (PID=1631) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:30:33,159] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:30:33,160] {logging_mixin.py:115} INFO - [2022-11-29 16:30:33,160] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:30:33,161] {logging_mixin.py:115} INFO - [2022-11-29 16:30:33,161] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:30:33,161] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:30:33,174] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 16:31:03,232] {processor.py:153} INFO - Started process (PID=1650) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:31:03,233] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:31:03,233] {logging_mixin.py:115} INFO - [2022-11-29 16:31:03,233] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:31:03,234] {logging_mixin.py:115} INFO - [2022-11-29 16:31:03,234] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:31:03,234] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:31:03,246] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 16:31:33,308] {processor.py:153} INFO - Started process (PID=1678) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:31:33,308] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:31:33,309] {logging_mixin.py:115} INFO - [2022-11-29 16:31:33,309] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:31:33,310] {logging_mixin.py:115} INFO - [2022-11-29 16:31:33,310] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:31:33,310] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:31:33,321] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 16:32:03,396] {processor.py:153} INFO - Started process (PID=1706) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:32:03,401] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:32:03,402] {logging_mixin.py:115} INFO - [2022-11-29 16:32:03,402] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:32:03,406] {logging_mixin.py:115} INFO - [2022-11-29 16:32:03,406] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:32:03,406] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:32:03,418] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.024 seconds
[2022-11-29 16:32:33,468] {processor.py:153} INFO - Started process (PID=1734) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:32:33,468] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:32:33,468] {logging_mixin.py:115} INFO - [2022-11-29 16:32:33,468] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:32:33,469] {logging_mixin.py:115} INFO - [2022-11-29 16:32:33,469] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:32:33,470] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:32:33,482] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.016 seconds
[2022-11-29 16:33:03,606] {processor.py:153} INFO - Started process (PID=1753) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:33:03,611] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:33:03,612] {logging_mixin.py:115} INFO - [2022-11-29 16:33:03,612] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:33:03,613] {logging_mixin.py:115} INFO - [2022-11-29 16:33:03,613] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:33:03,613] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:33:03,625] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.022 seconds
[2022-11-29 16:33:33,674] {processor.py:153} INFO - Started process (PID=1781) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:33:33,679] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:33:33,679] {logging_mixin.py:115} INFO - [2022-11-29 16:33:33,679] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:33:33,680] {logging_mixin.py:115} INFO - [2022-11-29 16:33:33,680] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:33:33,681] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:33:33,693] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 16:34:03,759] {processor.py:153} INFO - Started process (PID=1809) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:34:03,764] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:34:03,764] {logging_mixin.py:115} INFO - [2022-11-29 16:34:03,764] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:34:03,766] {logging_mixin.py:115} INFO - [2022-11-29 16:34:03,765] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:34:03,766] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:34:03,778] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 16:34:33,835] {processor.py:153} INFO - Started process (PID=1828) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:34:33,841] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:34:33,842] {logging_mixin.py:115} INFO - [2022-11-29 16:34:33,841] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:34:33,846] {logging_mixin.py:115} INFO - [2022-11-29 16:34:33,845] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:34:33,846] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:34:33,858] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.025 seconds
[2022-11-29 16:35:03,920] {processor.py:153} INFO - Started process (PID=1856) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:35:03,926] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:35:03,927] {logging_mixin.py:115} INFO - [2022-11-29 16:35:03,927] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:35:03,931] {logging_mixin.py:115} INFO - [2022-11-29 16:35:03,931] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:35:03,931] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:35:03,942] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.023 seconds
[2022-11-29 16:35:34,007] {processor.py:153} INFO - Started process (PID=1883) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:35:34,007] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:35:34,007] {logging_mixin.py:115} INFO - [2022-11-29 16:35:34,007] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:35:34,008] {logging_mixin.py:115} INFO - [2022-11-29 16:35:34,008] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:35:34,008] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:35:34,020] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.018 seconds
[2022-11-29 16:36:04,080] {processor.py:153} INFO - Started process (PID=1911) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:36:04,085] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:36:04,085] {logging_mixin.py:115} INFO - [2022-11-29 16:36:04,085] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:36:04,086] {logging_mixin.py:115} INFO - [2022-11-29 16:36:04,086] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:36:04,087] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:36:04,099] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 16:36:34,147] {processor.py:153} INFO - Started process (PID=1930) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:36:34,147] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:36:34,147] {logging_mixin.py:115} INFO - [2022-11-29 16:36:34,147] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:36:34,149] {logging_mixin.py:115} INFO - [2022-11-29 16:36:34,148] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:36:34,149] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:36:34,160] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 16:37:04,228] {processor.py:153} INFO - Started process (PID=1958) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:37:04,233] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:37:04,234] {logging_mixin.py:115} INFO - [2022-11-29 16:37:04,234] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:37:04,238] {logging_mixin.py:115} INFO - [2022-11-29 16:37:04,238] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:37:04,238] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:37:04,250] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.024 seconds
[2022-11-29 16:37:34,301] {processor.py:153} INFO - Started process (PID=1986) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:37:34,303] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:37:34,303] {logging_mixin.py:115} INFO - [2022-11-29 16:37:34,303] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:37:34,311] {logging_mixin.py:115} INFO - [2022-11-29 16:37:34,308] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:37:34,312] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:37:34,341] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.041 seconds
[2022-11-29 16:38:04,376] {processor.py:153} INFO - Started process (PID=2005) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:38:04,377] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 16:38:04,377] {logging_mixin.py:115} INFO - [2022-11-29 16:38:04,377] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:38:04,378] {logging_mixin.py:115} INFO - [2022-11-29 16:38:04,378] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 16:38:04,379] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 16:38:04,390] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.016 seconds
[2022-11-29 17:11:26,637] {processor.py:153} INFO - Started process (PID=41) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:11:26,638] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:11:26,639] {logging_mixin.py:115} INFO - [2022-11-29 17:11:26,639] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:11:26,643] {logging_mixin.py:115} INFO - [2022-11-29 17:11:26,642] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:11:26,643] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:11:26,664] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.034 seconds
[2022-11-29 17:11:56,718] {processor.py:153} INFO - Started process (PID=68) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:11:56,724] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:11:56,725] {logging_mixin.py:115} INFO - [2022-11-29 17:11:56,725] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:11:56,729] {logging_mixin.py:115} INFO - [2022-11-29 17:11:56,728] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:11:56,729] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:11:56,741] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.024 seconds
[2022-11-29 17:12:26,791] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:12:26,797] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:12:26,798] {logging_mixin.py:115} INFO - [2022-11-29 17:12:26,797] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:12:26,802] {logging_mixin.py:115} INFO - [2022-11-29 17:12:26,801] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:12:26,802] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:12:26,814] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.024 seconds
[2022-11-29 17:12:56,878] {processor.py:153} INFO - Started process (PID=115) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:12:56,879] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:12:56,880] {logging_mixin.py:115} INFO - [2022-11-29 17:12:56,880] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:12:56,885] {logging_mixin.py:115} INFO - [2022-11-29 17:12:56,884] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:12:56,885] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:12:56,922] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.050 seconds
[2022-11-29 17:13:26,956] {processor.py:153} INFO - Started process (PID=141) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:13:26,962] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:13:26,963] {logging_mixin.py:115} INFO - [2022-11-29 17:13:26,963] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:13:26,967] {logging_mixin.py:115} INFO - [2022-11-29 17:13:26,966] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:13:26,967] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:13:26,978] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.023 seconds
[2022-11-29 17:13:57,052] {processor.py:153} INFO - Started process (PID=171) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:13:57,057] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:13:57,057] {logging_mixin.py:115} INFO - [2022-11-29 17:13:57,057] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:13:57,059] {logging_mixin.py:115} INFO - [2022-11-29 17:13:57,058] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:13:57,059] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:13:57,071] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.020 seconds
[2022-11-29 17:14:27,154] {processor.py:153} INFO - Started process (PID=190) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:14:27,155] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:14:27,156] {logging_mixin.py:115} INFO - [2022-11-29 17:14:27,156] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:14:27,163] {logging_mixin.py:115} INFO - [2022-11-29 17:14:27,161] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:14:27,164] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:14:27,211] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.063 seconds
[2022-11-29 17:14:57,271] {processor.py:153} INFO - Started process (PID=218) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:14:57,272] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:14:57,272] {logging_mixin.py:115} INFO - [2022-11-29 17:14:57,272] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:14:57,274] {logging_mixin.py:115} INFO - [2022-11-29 17:14:57,273] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:14:57,274] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:14:57,287] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.018 seconds
[2022-11-29 17:15:27,351] {processor.py:153} INFO - Started process (PID=236) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:15:27,352] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:15:27,352] {logging_mixin.py:115} INFO - [2022-11-29 17:15:27,352] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:15:27,353] {logging_mixin.py:115} INFO - [2022-11-29 17:15:27,353] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:15:27,353] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:15:27,365] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.019 seconds
[2022-11-29 17:15:57,412] {processor.py:153} INFO - Started process (PID=263) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:15:57,413] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:15:57,413] {logging_mixin.py:115} INFO - [2022-11-29 17:15:57,413] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:15:57,414] {logging_mixin.py:115} INFO - [2022-11-29 17:15:57,414] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:15:57,415] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:15:57,427] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.016 seconds
[2022-11-29 17:16:27,493] {processor.py:153} INFO - Started process (PID=291) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:16:27,493] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:16:27,493] {logging_mixin.py:115} INFO - [2022-11-29 17:16:27,493] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:16:27,495] {logging_mixin.py:115} INFO - [2022-11-29 17:16:27,494] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:16:27,495] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:16:27,507] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.016 seconds
[2022-11-29 17:16:57,568] {processor.py:153} INFO - Started process (PID=309) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:16:57,568] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:16:57,568] {logging_mixin.py:115} INFO - [2022-11-29 17:16:57,568] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:16:57,570] {logging_mixin.py:115} INFO - [2022-11-29 17:16:57,570] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:16:57,570] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:16:57,585] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.019 seconds
[2022-11-29 17:17:27,632] {processor.py:153} INFO - Started process (PID=337) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:17:27,632] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:17:27,633] {logging_mixin.py:115} INFO - [2022-11-29 17:17:27,633] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:17:27,636] {logging_mixin.py:115} INFO - [2022-11-29 17:17:27,635] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:17:27,636] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:17:27,648] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.017 seconds
[2022-11-29 17:17:57,703] {processor.py:153} INFO - Started process (PID=357) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:17:57,704] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:17:57,704] {logging_mixin.py:115} INFO - [2022-11-29 17:17:57,704] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:17:57,705] {logging_mixin.py:115} INFO - [2022-11-29 17:17:57,705] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:17:57,705] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:17:57,718] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.016 seconds
[2022-11-29 17:18:27,785] {processor.py:153} INFO - Started process (PID=385) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:18:27,786] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:18:27,786] {logging_mixin.py:115} INFO - [2022-11-29 17:18:27,786] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:18:27,787] {logging_mixin.py:115} INFO - [2022-11-29 17:18:27,787] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:18:27,787] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:18:27,799] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 17:18:57,853] {processor.py:153} INFO - Started process (PID=413) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:18:57,853] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:18:57,853] {logging_mixin.py:115} INFO - [2022-11-29 17:18:57,853] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:18:57,855] {logging_mixin.py:115} INFO - [2022-11-29 17:18:57,854] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:18:57,855] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:18:57,890] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.039 seconds
[2022-11-29 17:19:27,922] {processor.py:153} INFO - Started process (PID=432) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:19:27,923] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:19:27,923] {logging_mixin.py:115} INFO - [2022-11-29 17:19:27,923] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:19:27,926] {logging_mixin.py:115} INFO - [2022-11-29 17:19:27,925] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:19:27,926] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:19:27,942] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.023 seconds
[2022-11-29 17:19:58,017] {processor.py:153} INFO - Started process (PID=459) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:19:58,017] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:19:58,017] {logging_mixin.py:115} INFO - [2022-11-29 17:19:58,017] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:19:58,019] {logging_mixin.py:115} INFO - [2022-11-29 17:19:58,018] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:19:58,019] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:19:58,030] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.015 seconds
[2022-11-29 17:20:28,100] {processor.py:153} INFO - Started process (PID=478) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:20:28,101] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:20:28,101] {logging_mixin.py:115} INFO - [2022-11-29 17:20:28,101] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:20:28,104] {logging_mixin.py:115} INFO - [2022-11-29 17:20:28,103] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:20:28,104] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:20:28,123] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.026 seconds
[2022-11-29 17:20:58,184] {processor.py:153} INFO - Started process (PID=505) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:20:58,185] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:20:58,186] {logging_mixin.py:115} INFO - [2022-11-29 17:20:58,186] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:20:58,190] {logging_mixin.py:115} INFO - [2022-11-29 17:20:58,189] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:20:58,190] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:20:58,210] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.033 seconds
[2022-11-29 17:21:28,295] {processor.py:153} INFO - Started process (PID=525) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:21:28,296] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:21:28,297] {logging_mixin.py:115} INFO - [2022-11-29 17:21:28,297] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:21:28,303] {logging_mixin.py:115} INFO - [2022-11-29 17:21:28,301] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:21:28,304] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:21:28,333] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.046 seconds
[2022-11-29 17:21:58,370] {processor.py:153} INFO - Started process (PID=553) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:21:58,371] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:21:58,373] {logging_mixin.py:115} INFO - [2022-11-29 17:21:58,372] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:21:58,379] {logging_mixin.py:115} INFO - [2022-11-29 17:21:58,377] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:21:58,380] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:21:58,412] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.050 seconds
[2022-11-29 17:22:28,450] {processor.py:153} INFO - Started process (PID=582) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:22:28,456] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:22:28,456] {logging_mixin.py:115} INFO - [2022-11-29 17:22:28,456] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:22:28,457] {logging_mixin.py:115} INFO - [2022-11-29 17:22:28,457] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 53
    with dag as DAG(
        ^
SyntaxError: can't assign to function call
[2022-11-29 17:22:28,458] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:22:28,469] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
[2022-11-29 17:22:53,505] {processor.py:153} INFO - Started process (PID=601) to work on /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:22:53,510] {processor.py:641} INFO - Processing file /opt/airflow/dags/update_currency_values_dag.py for tasks to queue
[2022-11-29 17:22:53,511] {logging_mixin.py:115} INFO - [2022-11-29 17:22:53,511] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:22:53,512] {logging_mixin.py:115} INFO - [2022-11-29 17:22:53,511] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/update_currency_values_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_currency_values_dag.py", line 62
    t1 = PythonOperator(
    ^
IndentationError: unexpected indent
[2022-11-29 17:22:53,512] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/update_currency_values_dag.py
[2022-11-29 17:22:53,525] {processor.py:161} INFO - Processing /opt/airflow/dags/update_currency_values_dag.py took 0.021 seconds
