[2022-11-30 10:31:27,796] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: main_dag.create_currency_schema manual__2022-11-30T10:31:25.627340+00:00 [queued]>
[2022-11-30 10:31:27,805] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: main_dag.create_currency_schema manual__2022-11-30T10:31:25.627340+00:00 [queued]>
[2022-11-30 10:31:27,805] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-30 10:31:27,805] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-11-30 10:31:27,805] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-30 10:31:27,819] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_currency_schema> on 2022-11-30 10:31:25.627340+00:00
[2022-11-30 10:31:27,825] {standard_task_runner.py:52} INFO - Started process 114 to run task
[2022-11-30 10:31:27,828] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_currency_schema', 'manual__2022-11-30T10:31:25.627340+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmppti4dd7v', '--error-file', '/tmp/tmpebg3wgte']
[2022-11-30 10:31:27,829] {standard_task_runner.py:80} INFO - Job 56: Subtask create_currency_schema
[2022-11-30 10:31:27,887] {task_command.py:371} INFO - Running <TaskInstance: main_dag.create_currency_schema manual__2022-11-30T10:31:25.627340+00:00 [running]> on host 83e6a62957c2
[2022-11-30 10:31:27,939] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ricardo
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_currency_schema
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T10:31:25.627340+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T10:31:25.627340+00:00
[2022-11-30 10:31:27,940] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-11-30 10:31:27,941] {base.py:68} INFO - Using connection ID 'production_postgres' for task execution.
[2022-11-30 10:31:27,942] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 204, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "db" (172.20.0.2), port 5439 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2022-11-30 10:31:27,947] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=main_dag, task_id=create_currency_schema, execution_date=20221130T103125, start_date=20221130T103127, end_date=20221130T103127
[2022-11-30 10:31:27,955] {standard_task_runner.py:97} ERROR - Failed to execute job 56 for task create_currency_schema (connection to server at "db" (172.20.0.2), port 5439 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 114)
[2022-11-30 10:31:27,999] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-30 10:31:28,065] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
